#!/usr/bin/env bash
#
export VERBOSITY
VERBOSITY=0
#-------------------------------------------------------------------------------
# Documentation
#-------------------------------------------------------------------------------
cat <<'EOD' >/dev/null

There's more than aliases here and we invoke some other files under found under
the portable-scripts repository in the following order:

1. bash_debug -- if executable
2. functions -- sets functions for use in scripting
3. env -- sets environment variables
4. -- body of aliases happens after the above
5. bash_paths -- sets additional environment variables (usually with dependencies)

EOD
#-------------------------------------------------------------------------------
export PORTABLE_SCRIPTS_HOME
PORTABLE_SCRIPTS_HOME="${PORTABLE_SCRIPTS_HOME:-${HOME}/.portable-scripts}"
PORTABLE_DOTFILES="${PORTABLE_SCRIPTS_HOME}/dotfiles"
PORTABLE_SCRIPTS="${PORTABLE_SCRIPTS_HOME}/scripts"
#  #####  #####  ##### #     #    # ####   #####                                 
#  #    # #    # #     #     #    # #   #  #                                     
#  #    # #    # #     #     #    # #    # #                                     
#  #####  #####  ##### #     #    # #    # #####                                 
#  #      #  #   #     #     #    # #    # #                                     
#  #      #   #  #     #     #    # #   #  #                                     
#  #      #    # ##### #####  ####  ####   #####                                 
#-------------------------------------------------------------------------------
if [[ -z "${ALIAS_SCRIPT:-}" && -n "${script:-}" ]]; then
  export ALIAS_SCRIPT
  ALIAS_SCRIPT="${script}"
fi

export SCRIPT_NAME SCRIPT_PATH
# shellcheck source=/dev/null
source "${PORTABLE_SCRIPTS}/Essential-IO"
for SCRIPT_NAME in "bash_debug" "functions" "env"; do
  SCRIPT_PATH="${PORTABLE_DOTFILES}/${SCRIPT_NAME}"
  if [[ -x "${SCRIPT_PATH}" ]]; then
    # shellcheck disable=SC2154
    if [[ "${BASH_DEBUG}" == 1 ]]; then Report_debug "source ${SCRIPT_PATH}"; fi
    # shellcheck disable=SC1090
    source "${SCRIPT_PATH}"
  fi
  SCRIPT_PATH="${HOME}/.${SCRIPT_NAME}-local"
  if [[ -x "${SCRIPT_PATH}" ]]; then
    # shellcheck disable=SC2154
    if [[ "${BASH_DEBUG}" == 1 ]]; then Report_debug "source ${SCRIPT_PATH}"; fi
    # shellcheck disable=SC1090
    source "${SCRIPT_PATH}"
  fi
done

# enable color support of ls and also add handy aliases
if [[ -r ~/.dircolors ]]; then
  EVAL_TEXT="$(dircolors -b ~/.dircolors)" || EVAL_TEXT="$(dircolors -b)"
  eval "${EVAL_TEXT}"
fi

# shellcheck source=/dev/null
source "${PORTABLE_DOTFILES}/aliases"

#-------------------------------------------------------------------------------
#  #####   ####   ####  #######    #    #     # #####  #     #####               
#  #    # #    # #    #    #      # #   ##   ## #    # #     #                   
#  #    # #    # #         #     #   #  # # # # #    # #     #                   
#  #####  #    #  ####     #    #     # #  #  # #####  #     #####               
#  #      #    #      #    #    ####### #     # #    # #     #                   
#  #      #    # #    #    #    #     # #     # #    # #     #                   
#  #       ####   ####     #    #     # #     # #####  ##### #####               
#-------------------------------------------------------------------------------
# shellcheck disable=SC2043
for SCRIPT_NAME in bash_paths; do
  # shellcheck source=/dev/null
  SCRIPT_PATH="${PORTABLE_DOTFILES}/${SCRIPT_NAME}"
  if [[ -x "${SCRIPT_PATH}" ]]; then
    if [[ "${BASH_DEBUG}" == 1 ]]; then Report_debug "source ${SCRIPT_PATH}"; fi
    # shellcheck disable=SC1090
    source "${SCRIPT_PATH}"
  fi
done
unset SCRIPT_NAME SCRIPT_PATH

# vim:nospell
