#!/bin/bash
#
# FILE: .bash_profile

# This script sources bashrc and ensure the home directory is setup properly.
export HOME USER PORTABLE_SCRIPTS_HOME
USER="${USER:-$(whoami)}"
PORTABLE_SCRIPTS_HOME="${PORTABLE_SCRIPTS_HOME:-${HOME}/.portable-scripts}"

# Get the aliases and functions
if [[ -f ~/.bashrc ]]; then
  # shellcheck source=/dev/null
  source ~/.bashrc
fi

# User specific environment and startup programs

if [[ -d ~/bin ]]; then
  mkdir -p   ~/bin
  chmod g+s  ~/bin
  chmod a+rx ~/bin
fi

if [[ -d "${HOME}/.local" ]]; then
  mkdir -p "${HOME}/.local/bin"
fi

if [[ -d "${HOME}/.local/bin" ]]; then
  Prepend_path PATH "${HOME}/.local/bin"
  Prepend_path PATH "${HOME}/bin" # Allow user overrides
  MANPATH=~/man:"${PORTABLE_SCRIPTS_HOME}/man:/usr/local/share/man:/usr/share/man"
fi
export MANPATH
