#!/usr/bin/env bash
#
# A script to test the utils.bash functions and provide an example of usage

BINDIR="$(realpath $(dirname "$0")/../bin)"
UTILS_BASH="${BINDIR}/utils.bash"
if [[ -f "${UTILS_BASH}" ]]; then
  # shellcheck source ../bin/utils.bash
  source "${UTILS_BASH}" "$0"
else
  echo "Error: Missing ${UTILS_BASH}" 1>&2; exit 1
fi

echo xx "Testing Log; Echo; Info; Do; Ruler" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Log "This is logged only"
Echo -n "Testing "
Echo " Echo"
Info "Testing Info"
Do "echo Testing Do"
Info "Testing Ruler +; / Message; - Message"
Do Ruler +
Do Ruler -grn / Hello there
Do Ruler Hello there

Ruler -cyn _ "Testing Pass; Fail; PassFail"
if Pass; then echo Pass; else echo Fail; fi
Do pwd && echo pwd passed
Do Fail 1 && echo Fail failed || echo Fail passed
Do Pass 1 && echo Pass passed || echo Pass failed
Do Fail 2; PassFail
Do Pass 2; PassFail

Ruler -cyn _ "Testing errors and warnings"
Error First Error 1
Error Second Error 2
Warn Warn about possible issues
Error Final Error 2
Ruler -red _ "Testing Summary; Die"
Summary
( Die Fatally; echo "Should not see this" )
Info "The end"
