#!/usr/bin/env bash
#
# A script to test Require

BINDIR="$(realpath $(dirname "$0")/../bin)"
UTILS_BASH="${BINDIR}/utils.bash"
if [[ -f "${UTILS_BASH}" ]]; then
  # shellcheck source ../bin/utils.bash
  source "${UTILS_BASH}" "$0"
else
  echo "Error: Missing ${UTILS_BASH}" 1>&2; exit 1
fi

Ruler -cyn _ "Testing Require & get-build-opts.bash"
GetBuildOpts "$0" "$@"

