#!/bin/bash
#
# A script to test Require

BINDIR="$(realpath $(dirname "$0")/../bin)"
REPORTING_BASH="${BINDIR}/reporting.bash"
if [[ -f "${REPORTING_BASH}" ]]; then
  # shellcheck source ../bin/reporting.bash
  source "${REPORTING_BASH}" "$0"
else
  echo "Error: Missing ${REPORTING_BASH}" 1>&2; exit 1
fi

Ruler -cyn _ "Testing Require & get-build-opts.bash"
# shellcheck source=../bin/get-build-opts.bash
Require get-build-opts.bash
GetBuildOpts "$0" "$@"

