#!/usr/bin/env bash

function findkey()
{
  # shellcheck disable=SC2034
  local COMMENT="
  Synopsis: Searches for an SSH key matching the provided string
  Syntax: findkey FINGERPRINT
  "
  local k f
  for k in ~/.ssh/*.pub; do
    f="$(ssh-keygen -l -E md5 -f "${k}" 2>/dev/null)" 
    if [[ "${f}" =~ $1 ]]; then
      echo "${k} -> ${f}"
    fi
  done
}
