#!/usr/bin/env bash

#-------------------------------------------------------------------------------
if builtin command -v "realpath" 1>/dev/null; then
  # Faster version in Linux
  function Realpath ()
  {
    #@ Output the realpath name treating all arguments as a single filename specification
    #| Realpath FILENAME_SPECIFICATION
    if [[ $# == 0 ]]; then set - .; fi
    if [[ -e "$*" ]]; then realpath -q "$@"; else echo ""; fi
  }
else
  function Realpath ()
  {
    #@ Output the realpath name treating all arguments as a single filename specification
    #| Realpath FILENAME_SPECIFICATION
    if [[ $# == 0 ]]; then set - .; fi
    perl -MCwd=abs_path -le '$p=abs_path(join(q( ),@ARGV));print $p if -e $p' "$*"
  }
fi

