#!/usr/bin/env bash

function Add_prefix() {
  if [[ $# -lt 2 ]]; then Error "$0 needs at least two arguments"; return; fi
  local prefix="$1"
  shift
  for element in "$@"; do
    echo "${prefix}${element}"
  done
}
