#!/usr/bin/env bash

function Append_path() # only if 2nd arg does not exist in first
{
  Usage "$1" "Append_path VAR PATH" || return 1
  if [[ $# != 2 ]]; then Error "Append_path requires two arguments"; return 1; fi
  local var arg plscript
  var="$1"
  arg="$(Realpath "$2")"; shift
  # shellcheck disable=SC2016
  plscript='$v=shift;$p=shift;$e=$ENV{$v};$e=~s/.$/$&:/;printf qq{%s="%s%s"; export %s},$v,$e,$p,$v;print ""'
  if ! Has_path "${var}" "${arg}"; then 
    local ASSIGNMENT
    ASSIGNMENT="$(perl -le "${plscript}" "${var}" "${arg}")"
    eval "${ASSIGNMENT}"
  fi
}

