#!/usr/bin/env bash

function Append_path() # only if 2nd arg does not exist in first
{
  #|Usage "$1" "Append_path VAR PATH" || return 1
  if [[ $# != 2 ]]; then Report_error "Append_path requires two arguments"; return 1; fi
  local VAR ARG
  VAR="$1"
  ARG="$(Realpath "$2")"; shift
  if ! Has_path "${VAR}" "${ARG}"; then 
     EVAL="${VAR}=\"\$${VAR}:${ARG}\"; export ${VAR}"
    eval "${EVAL}"
  fi
}

