#!/usr/bin/env bash
#
# Locate all instances of named script(s)
# Dependencies: Realpath Append_path

export FINDSCRIPT_COUNT SCRIPTDIRS

function FindScript()
{
  if [[ $# == 0 ]]; then
    Report_error "Syntax: FindScript SCRIPTNAME(S)"
    return 1
  fi
  export FINDSCRIPT_COUNT
  FINDSCRIPT_COUNT=0
  local DIR SCRIPT
  if [[ -n "${ZSH_VERSION}" ]]; then set -o shwordsplit ; fi
  #-----------------------------------------------------------------------------
  # Make sure we have directories to search
  #-----------------------------------------------------------------------------
  if [[ -z "${SCRIPTDIRS}" ]]; then
    # Missing SCRIPTDIRS! Attempt default locations.
    for DIR in ../scripts ~/scripts ~/.local/scripts ; do
      Append_path SCRIPTDIRS "${DIR}"
    done
  fi
  export SCRIPTDIRS
  #-----------------------------------------------------------------------------
  # Search
  #-----------------------------------------------------------------------------
  local prev_IFS
  prev_IFS="${IFS}"
  IFS=':'
  for DIR in ${SCRIPTDIRS}; do
    IFS="${prev_IFS}"
    for SCRIPT in "$@"; do
      SCRIPT="$(Realpath "${DIR}/${SCRIPT}")"
      if [[ -x "${SCRIPT}" ]]; then
        (( ++FINDSCRIPT_COUNT ))
        echo "${SCRIPT}"
      fi
    done
  done
  IFS="${prev_IFS}"
}

