#!/usr/bin/env bash

function Find() {
  local DIR_LIST
  if [[ "${SHELL}" =~ zsh ]]; then
    set -o shwordsplit
  fi
  while [[ -d "$1" ]]; do
    if [[ "$1" =~ ^- ]]; then
      break
    fi
    DIR_LIST="${DIR_LIST} $1"
    shift
  done
  if [[ -z "${DIR_LIST}" ]]; then
    DIR_LIST="."
  fi
  if [[ $# == 0 ]]; then
    find ${DIR_LIST} -type d -path '**/.snapshots' -prune -false -o -true
  else
    find ${DIR_LIST} -type d -path '**/.snapshots' -prune -false -o "$@"
  fi
}
