#!/usr/bin/env bash
#
# Locate all instances of named script(s)

export FINDSCRIPT_COUNT

function FindScript()
{
  if [[ $# == 0 ]]; then
    Error "Syntax: FindScript SCRIPTNAME(S)"
    return 1
  fi
  export FINDSCRIPT_COUNT
  FINDSCRIPT_COUNT=0
  local DIR SCRIPT
  if [[ "${SHELL}" =~ zsh ]]; then
    set -o shwordsplit
  fi
  #-----------------------------------------------------------------------------
  # Make sure we have directories to search
  #-----------------------------------------------------------------------------
  if [[ -z "${SCRIPTDIRS}" ]]; then
    # Missing SCRIPTDIRS! Attempt default locations.
    for DIR in "." "./scripts" "../scripts" "${HOME}/scripts" "${HOME}/.local/scripts" ; do
      if [[ -d "${DIR}" ]]; then
        if [[ -n "${SCRIPTDIRS}" ]]; then
          SCRIPTDIRS="${SCRIPTDIRS}:${DIR}"
        else
          SCRIPTDIRS="${DIR}"
        fi
      fi
    done
  fi
  export SCRIPTDIRS
  #-----------------------------------------------------------------------------
  # Search
  #-----------------------------------------------------------------------------
  local prev_IFS
  prev_IFS="${IFS}"
  IFS=':'
  for DIR in ${SCRIPTDIRS}; do
    IFS="${prev_IFS}"
    while [[ $# != 0 ]]; do
      SCRIPT="$(Realpath "${DIR}/$1")"
      if [[ -x "${SCRIPT}" ]]; then
        (( ++FINDSCRIPT_COUNT ))
        echo "${SCRIPT}"
      fi
      shift
    done
  done
  IFS="${prev_IFS}"
}

