#!/usr/bin/env bash

function Firstreal() {
  if [[ "${SHELL}" =~ zsh ]]; then
    set -o shwordsplit
  fi
  perl -le 'for(@ARGV){for my $p (split(qq{[\n\t ]+})){next unless -e $p;print $p;exit 0;}}' "$@"
}

