#!/usr/bin/env bash

function h() { # Display most recent N history lines
  if [[ -n "${ZSH_VERSION}" ]]; then set -o shwordsplit ; fi
  local N
  (( N = 4 - $(Rows) ))
  if [[ "$1" =~ ^-[0-9]+ ]]; then
    N="$1"
    shift
  fi
  history | perl -e 'for(reverse <>){next unless m/^ *\d+ +(.+)/;next if exists $p{$1};unshift @o,$_;$p{$1}++};for(@o){print}' | tail "${N}"
}
