#!/usr/bin/env bash

function h() { # Display most recent N history lines
  if [[ "${SHELL}" == /bin/zsh ]]; then
    set -o shwordsplit
  fi
  local N=-20
  if [[ "$1" =~ ^-[0-9]+ ]]; then
    N="$1"
    shift
  fi
  history "$@" | tail "${N}"
}
