#!/usr/bin/env bash

function Has_path() {
  #| USAGE: Has_path VAR PATH
  local arg plscript
  arg="$(Realpath "$2")"
  # shellcheck disable=SC2016
  plscript='$v=$ARGV[0]; $p=$ARGV[1]; for $d (split(qq{:},$ENV{$v})) { next if !-d $d; exit 0 if$p eq abs_path($d); } exit 1'
  if [[ -z "${arg}" ]]; then return 1; fi
  /usr/bin/perl -M'Cwd(abs_path)' -le "${plscript}" "$1" "${arg}"
}

