#!/usr/bin/env bash

export lwd nwd cws nws
function j() {
  # Synopsis
  #   j - more powerful alternative to cd (aka jump)
  # Syntax
  #   j DIR(S)
  # Begin parsing options
  #-----------------------------------------------------------------------------
  local J_VERBOSE J_DEBUG
  J_VERBOSE=0
  J_DEBUG=0
  # Setup favorites list if not defined via exported FAVS variable
  if [[ -z "${FAVS}" ]]; then
    local fav
    for fav in Favorites favs .favs; do
      FAVS="$(realpath "${HOME}/${fav}")"
      if [[ "${FAVS}" != "" ]]; then
        break
      fi
    done
    export FAVS
  fi
  if [[ $# != 0 ]]; then
    # Parse command-line options
    while [[ "$1" =~ ^-. ]]; do
      if [[ ${J_DEBUG} == 1 ]]; then Debug -f "$1"; fi
      case "$1" in
      -h | -help | --help) cat 1>&2 <<EOT
Synopsis
--------

  j - slightly more flexible alternative to change directory 'cd' command (uses cd internally).

Syntax
------

  j -help
  j -list
  j {dir_or_file}...

Description
-----------

  For each argument, j uses case-insensitive globbing to
  locate that element.

  If it finds a directory, then *j* moves to that directory
  (cd) and processes the next argument.

  If the result is a path to a non-directory element, then
  it jumps to the directory containing that element.

Examples
--------

  j tlm-? answers EX01
  j ~/syscfund/ex01/ex01.cpp

EOT
        return
        ;;
      -d | --debug )
        J_DEBUG=1
        ;;
      -v | --verbose )
        # shellcheck disable=SC2034
        J_VERBOSE=1
        ;;
      -l | -list )
        if [[ -n "${FAVS}" ]]; then
          /bin/ls "${FAVS}"
        else
          echo "No favorites directory specified" 1>&2
        fi
        return
        ;;
      -L | -lns )
        if [[ -n "${FAVS}" ]]; then
          /bin/ls -l "${FAVS}"
        else
          echo "No favorites directory specified" 1>&2
        fi
        return
        ;;
      -[1-9])
        ;;
      * ) 
        echo 1>&2 "ERROR: Unknown option $1"
        return
        ;;
      esac
      shift
    done
  fi
  test "${J_DEBUG}" = 1 && Debug -f "Debug on"
  test "${J_VERBOSE}" = 1 && Info "Verbose on"
  # End parsing options
  #-----------------------------------------------------------------------------
  local working_script='setup.profile'

  if [[ "${SHELL}" == /bin/zsh ]]; then
    set -o shwordsplit
    test "${J_DEBUG}" = 1 && Debug -f "Splitting"
  fi

  # Last working directory
  local prev_lwd="${lwd}"
  lwd="$(Realpath .)"
  export lwd
  if [[ $# == 0 ]]; then
    # shellcheck disable=SC2164
    cd
  else
    while [[ $# != 0 ]]; do
      test "${J_DEBUG}" = 1 && Debug -f "Arg '%s'" "$1"
      if [[ "$1" == '-' ]]; then
        # shellcheck disable=SC2164
        cd -
      else
        arg="$1"
        alt="$(perl -le '@d=glob(shift @ARGV);print shift @d' "$1")"
        if [[ ${J_DEBUG} == 1 ]]; then
          Debug -f "DEBUG: arg='%s'" "${arg}"
          Debug -f "DEBUG: alt='%s'" "${alt}"
        fi
        if [[ -e "${arg}" && -f "${arg}" ]]; then
          arg=$(dirname "${arg}")
        fi
        # ToDo: add case-insensitivity
        # shellcheck disable=SC2164
        cd "${arg}" 1>/dev/null 2>&1 \
        || cd "${alt}" 1>/dev/null 2>&1 \
        || break
      fi
      shift
    done
  fi
  test "${J_DEBUG}" = 1 && Debug -f "Saving working directory"
  # Save current location as the working directory
  local next_wd
  next_wd="$(Realpath .)"
  # Go back to original directory then forward to simulate a single jump
  # shellcheck disable=SC2164
  cd "${lwd}" 2>/dev/null 1>/dev/null
  # shellcheck disable=SC2164
  cd "${next_wd}"

  if [[ "${next_wd}" != "${prev_lwd}" ]]; then
    lwd="${prev_lwd}"
  else
    export cwd
    cwd="${next_wd}"
  fi
  test "${J_DEBUG}" = 1 && Debug -f "Landed %s" "$(pwd)"

  # Save last working script if it was previously set
  if [[ -n "${nws}" ]]; then export lws; lws="${nws}"; fi

  # Deal with new working script if it exists
  export nws
  nws="$(Firstreal "$(Add_suffix "/${working_script}" . .. ../.. ../../..)")"
  test "${J_DEBUG}" = 1 && Debug -f "Checking for working script nws=%s" "'${nws}'"
  if [[ -n "${nws}" ]]; then
    nws="$(Realpath "${nws}")"
    local LASTOK NEXTOK
    LASTOK=1 NEXTOK=1
    # Qualifications to use a working script:
    # 1. Must not be the same as the last working script
    # 2. Must be executable and not a directory
    # 3. Last script must support ACTION variable
    if [[ -n "${lws}" && "${lws}" == "${nws}" ]]; then
      test "${J_DEBUG}" = 1 && Debug -f "lws set and equal to nws ${nws}"
      LASTOK=0
      NEXTOK=0
    fi
    if [[ ! -x "${lws}" || -d "${lws}" ]]; then
      LASTOK=0
    fi
    if [[ ${LASTOK} == 1 ]]; then
      if grep -q ACTION "${lws}"; then
        LASTOK=1
      else
        LASTOK=0
      fi
    fi
    if [[ ! -x "${nws}" || -d "${nws}" ]]; then
      NEXTOK=0
      test "${J_DEBUG}" = 1 && Debug -f "nws not executable or is a directory ${nws}"
    fi
    # Source old working script with ACTION='rm'
    if [[ ${LASTOK} == 1 ]]; then
      test "${J_VERBOSE}" = 1 && Info "Removing ${nws}"
      export ACTION
      ACTION='rm'
      # shellcheck disable=SC1090
      source "${nws}"
      unset ACTION
    fi
    # Source new working script
    if [[ ${NEXTOK} == 1 ]]; then
      test "${J_VERBOSE}" = 1 && Info "Adding ${nws}"
      export ACTION
      ACTION='add'
      # shellcheck disable=SC1090
      source "${nws}"
      unset ACTION
    fi
  fi
  if [[ -n "$(command -v set_title)" ]]; then
    set_title "$(pwd)"
  fi
  if [[ -n "$(command -v set_icon)" ]]; then
    set_icon "$(basename "$(pwd)")"
  fi
}
