#!/usr/bin/env bash

function lns() { # Display symbolic links
  if [[ "${SHELL}" =~ zsh ]]; then
    set -o shwordsplit
  fi
  if [[ $# == 0 ]]; then
    # shellcheck disable=SC2012
    ls -lA | cut -c 40- | grep -F -- '->'
  else
    for arg in "$@"; do
      if [[ -L "${arg}" ]]; then
        printf "%s -> %s\n" "${arg}" "$(Realpath "${arg}")"
      elif [[ -d "${arg}" ]]; then
        local dir
        dir="$(Realpath "${arg}")"
        find "${dir}" -type l -print0 | while IFS= read -r -d '' full; do 
          link="$(perl -le 'my($b,$h)=@ARGV;$h=~s{^$b/}{};print $h' "${dir}" "${full}")"
          printf "%s -> %s\n" "${link}" "$(Realpath "${full}")"
        done
      else
        printf "%s -> ?\n" "${arg}"
      fi
    done | sort | grep -F -- '->'
  fi
}
