#!/usr/bin/env bash
#
# Load a script (do NOT execute)

export LOADED

function Run() {
  Load "$1"
  "$@"
}

function Load() {
  export Load_VERSION=1.4
  #|Usage "$1" "Load [-v][-n] SCRIPTNAME(S)" || return 0
  # Dependencies: Firstreal, FindScript, Report_info, Report_warning, Report_error
  local VERBOSITY NOTREALLY DIR SCRIPT STATUS prev_NOAUTORUN
  VERBOSITY=0
  NOTREALLY=0
  STATUS=0
  while [[ $# -gt 0 ]]; do
    Report_info "Loading $1"
    while [[ "$1" =~ ^- ]]; do
      case "$1" in
        -n) NOTREALLY=1 ;;
        -v) VERBOSITY=1 ; Report_info "Verbosity ${VERBOSITY}";;
        -q) VERBOSITY=0 ;;
         *) return 1 ;;
      esac
      shift
    done
    if [[ "${SHELL}" =~ zsh ]]; then
      set -o shwordsplit
    fi
    SCRIPT="$(FindScript "$1")"
    SCRIPT="$(Firstreal "${SCRIPT}")"
    if [[ -z "${SCRIPT}" ]]; then
      Report_error "Unable to find suitable script '$1'"
      return 1
    fi
    prev_NOAUTORUN=""
    if [[ -n "${NOAUTORUN}" ]]; then prev_NOAUTORUN="${NOAUTORUN}" ; fi
    NOAUTORUN=1
    export NOAUTORUN
    if [[ ${NOTREALLY} == 1 ]]; then
      Report_info -tag % "source ${SCRIPT}" ;
      return 0
    fi
    # shellcheck disable=SC1090
    if ! source "${SCRIPT}"; then
      (( STATUS=STATUS | $? ))
      Report_warning "Failed to load ${SCRIPT}"
    elif [[ ${VERBOSITY} -gt 0 ]]; then
      Report_info "Loaded ${SCRIPT}"
    fi
    if [[ -n "${prev_NOAUTORUN}" ]]; then NOAUTORUN="${prev_NOAUTORUN}" ; else unset NOAUTORUN ; fi
    shift
  done
  return "${STATUS}"
}

function Unload()
{
  true
}

function Reload()
{
  #|Usage "$1" "Reload [-v]" || return
  local VERBOSITY DIR NAME SCRIPT
  VERBOSITY=0
  if [[ "$1" == "-v" ]]; then
    VERBOSITY=1
    shift
  fi
  if [[ "${SHELL}" == /bin/zsh ]]; then
    set -o shwordsplit
  fi
  local FUNCS
  FUNCS=$(declare -f | perl -lane 'next unless m-^[[:alpha:]]{2,} *\(\) ?[\{]-;print $F[0]')
  if [[ -z "${SCRIPTDIRS+x}" ]]; then
    # Missing SCRIPTDIRS! Attempt default locations.
    for DIR in "${HOME}/scripts" "${HOME}/.local/scripts" ; do
      if [[ -d "${DIR}" ]]; then
        if [[ "${SCRIPTDIRS}" =~ : ]]; then
          SCRIPTDIRS="${SCRIPTDIRS}:${DIR}"
        else
          SCRIPTDIRS="${DIR}"
        fi
      fi
    done
  fi
  export SCRIPTDIRS
  local prev_IFS
  prev_IFS="${IFS}"
  IFS=':'
  local prev_NOAUTORUN
  prev_NOAUTORUN=""
  if [[ -n "${NOAUTORUN}" ]]; then
    prev_NOAUTORUN="${NOAUTORUN}"
  fi
  NOAUTORUN=1
  export NOAUTORUN
  for DIR in ${SCRIPTDIRS}; do
    IFS="${prev_IFS}"
    for NAME in ${FUNCS}; do
      SCRIPT="${DIR}/${NAME}"
      if [[ -x "${SCRIPT}" ]]; then
        if [[ ${VERBOSITY} -gt 0 ]]; then
          Report_info "Loading ${SCRIPT}"
        fi
        # shellcheck disable=SC1090
        source "${SCRIPT}"
      fi
    done
  done
  if [[ -n "${prev_NOAUTORUN}" ]]; then
    NOAUTORUN="${prev_NOAUTORUN}"
  else
    unset NOAUTORUN
  fi
}

# vim:nospell
