#!/usr/bin/env bash

function lx() { # Display last N files (default 30) sorted by modification time
  N=-30
  if [[ "$1" =~ ^-[0-9]+ ]]; then
    N="$1"
    shift
  fi
  /bin/ls -lt "$@" | head "${N}"
}
