#!/usr/bin/env bash

Load Read
Load Confirm

function Die() { echo "FAILED to build! $*" 1>&2; return 1; }

#-------------------------------------------------------------------------------
function Mk()
{
  export GITROOT_DIR GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL
  GITROOT_DIR="$(git rev-parse --show-toplevel)" || Die "Not in git repo"
  if [[ "${USER}" == user || -z "${GIT_COMMITTER_NAME}" || -z "${GIT_COMMITTER_EMAIL}" ]];then
    while [[ -z "${GIT_COMMITTER_NAME}" ]]; do
      REPLY=""
      if [[ -z "${REPLY}" ]]; then
        Read "What's your full name?"
        if Confirm "Is ${REPLY} correct (y|n)?"; then
          GIT_COMMITTER_NAME="${REPLY}"
        else
          REPLY=""
        fi
      fi
    done
    while [[ -z "${GIT_COMMITTER_EMAIL}" ]]; do
      REPLY=""
      if [[ -z "${REPLY}" ]]; then
        Read "What's your proper work e-mail address?"
        if [[ "${REPLY}" =~ ^[A-Za-z]+[-A-Za-z0-9_.]+[A-Za-z0-9][@]doulos[.]com$ ]]; then
          if Confirm "Is ${REPLY} correct (y|n)?"; then
            GIT_COMMITTER_EMAIL="${REPLY}"
          else
            echo "Please specify a valid e-mail address"
            REPLY=""
          fi
        else
          REPLY=""
        fi
      fi
    done
  fi
  env DEVELOPER="${GIT_COMMITTER_EMAIL}" make -f "${GITROOT_DIR}/GNUmakefile" "$@"
}
