#!/usr/bin/env bash

function Prepend_path() # only if 2nd arg does not exist in first
{
  export Prepend_path_VERSION=1.4
  export ACTION
  #|Usage "$1" "Prepend_path VAR PATH" || return 1
  # Dependencies: Realpath Has_path Report_error Remove_path Unique_path
  if [[ "$1" == "-undo" || "${ACTION}" == "rm" ]]; then
    shift
    Remove_path "$1" "$2"
  else
    local VAR VAL SEP ARG EVAL
    SEP=''
    if [[ "$1" == "-sep" ]]; then
      SEP="$2"
      shift; shift
    fi
    if [[ $# != 2 ]]; then Report_error "Prepend_path requires two arguments"; return 1; fi
    VAR="$1"
    ARG="$(Realpath "$2")"; shift
    EVAL="VAL=\$${VAR}"
    eval "${EVAL}"
    if [[ -z "${SEP}" ]]; then
      if [[ "${VAL}" =~ .*[:].* ]]; then
        SEP=';'
      else
        SEP=':'
      fi
    fi
    if [[ -z "${VAL}" ]]; then
      EVAL="${VAR}=\"${ARG}\"; export ${VAR}"
    else
      EVAL="${VAR}=\"${ARG}${SEP}\$${VAR}\"; export ${VAR}"
    fi
    eval "${EVAL}"
    Unique_path "${VAR}"
  fi
}

