#!/usr/bin/env bash

function Prepend_path() { # only if 2nd arg does not exist in first
  export Prepend_path_VERSION=1.4
  #|Usage "$1" "Prepend_path VAR PATH" || return 1
  # Dependencies: Realpath Has_path Report_error Remove_path Unique_path
  if [[ "$1" == "-undo" ]]; then
    shift
    Remove_path "$1" "$2"
  else
    if [[ $# != 2 ]]; then Report_error "Prepend_path requires two arguments"; return 1; fi
    local VAR ARG EVAL
    VAR="$1"
    ARG="$(Realpath "$2")"; shift
    EVAL="${VAR}=\"${ARG}:\$${VAR}\"; export ${VAR}"
    eval "${EVAL}"
    Unique_path "${VAR}"
  fi
}

