#!/usr/bin/env bash

function Prepend_path() { # only if 2nd arg does not exist in first
  #|Usage "$1" "Prepend_path VAR PATH" || return 1
  if [[ $# != 2 ]]; then Report_error "Prepend_path requires two arguments"; return 1; fi
  local VAR ARG EVAL
  VAR="$1"
  ARG="$(Realpath "$2")"; shift
  # shellcheck disable=SC2016
  if ! Has_path "${VAR}" "${ARG}"; then
     EVAL="${VAR}=\"${ARG}:\$${VAR}\"; export ${VAR}"
     eval "${EVAL}"
  fi
}

