#!/usr/bin/env bash

function Unique_list() {
  if [[ "${SHELL}" == /bin/zsh ]]; then
    set -o shwordsplit
  fi
  perl -e 'for $e (@ARGV){next if exists $u{$e};$u{$e}=1;push @o,$e;}print join("\n",@o),"\n";' "$@"
}

