#!/usr/bin/env bash

#-------------------------------------------------------------------------------
#     #    #     ###    #     ####  #####  ####                                  
#    # #   #      #    # #   #    # #     #    #                                 
#   #   #  #      #   #   #  #      #     #                                      
#  #     # #      #  #     #  ####  #####  ####                                  
#  ####### #      #  #######      # #          #                                 
#  #     # #      #  #     # #    # #     #    #                                 
#  #     # ##### ### #     #  ####  #####  ####                                  
#-------------------------------------------------------------------------------
alias ls='ls -ABCF --color=always'
alias la='ls -A'
alias ll='ls -l'
alias dir='dir --color=auto'
alias m='less'
alias W='command -V'
alias agl='ag -l --nocolor'
alias cls='clear ; '
function Open()
{
  local OS arg
  OS="$(uname -a)"
  if [[ "${OS}" =~ ^.*Darwin.*$ ]]; then
    /usr/bin/open "$@"
  elif [[ "${OS}" =~ WSL2 ]]; then
    for arg in "$@"; do
      if [[ "${arg}" =~ [.]git$ ]]; then
        tower "${arg}"
      elif [[ -d "${arg}" ]]; then
        explorer "${arg}"
      elif [[ "${arg}" =~ [.]md$ ]]; then
        typora "${arg}"
      elif [[ "${arg}" =~ akefile$ ]]; then
        gvim "${arg}"
      elif [[ "${arg}" =~ [.](txt|h|hpp|c|cpp|rs|bash|sh|zsh|py)$ ]]; then
        gvim "${arg}"
      else
        explorer "${arg}"
      fi
    done
  elif [[ "${OS}" =~ ubuntu ]]; then
    for arg in "$@"; do
      if [[ -d "${arg}" ]]; then
        caja "${arg}"
      else
        caja "${arg}"
      fi
    done
  else
    Report_error "Not sure what to open"
  fi
}
# shellcheck disable=SC2154
alias vivado-setup='source "${APPS}"/xilinx/2020.1/Vivado/2020.1/settings64.sh'
export VI='vim'
alias vial='"${VI}"    -f "$(dotfile aliases)";        source "$(dotfile aliases)"'
alias vibash='"${VI}"  -f "$(dotfile bashrc)";         source "$(dotfile bashrc)"'
alias vienv='"${VI}"   -f "$(dotfile env)";        source "$(dotfile env)"'
alias vifuncs='"${VI}" -f "$(dotfile functions)"; source "${HOME}"/.functions'
alias vifstab="sudo vim /etc/fstab; sudo mount -a; ls /mnt/"
alias .alias='source "$(dotfile aliases)"'
alias .bash='source  "$(dotfile bashrc)"'
alias .env='source   "$(dotfile env)"'
alias .funcs='source "$(dotfile functions)"'
alias aliases='alias | /usr/bin/perl -pe "s/alias //;s/=.*//" | fmt'
alias funcs='declare -F|/usr/bin/perl -pe "s/declare -f//;"|fmt'
alias func='declare -f'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias rehash='hash -r'
alias Apt='sudo apt'
alias Dpkg='sudo dpkg'
alias Yum='sudo yum'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# vim:nospell
