# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# User specific aliases and functions

for script in bash_debug bash_env bash_aliases bash_functions bash_paths; do
  if [[ -x "${HOME}/${SCRIPT}" ]]; then
    if [[ "${BASH_DEBUG}" == 1 ]]; then REPORT_DEBUG "source ${HOME}/${SCRIPT}"; fi
    source "${HOME}/${SCRIPT}"
  fi
done

# The end
