# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
  . /etc/bashrc
fi

# User specific aliases and functions

export SCRIPT_NAME SCRIPT_PATH
for SCRIPT_NAME in bash_debug bash_env bash_aliases bash_functions bash_paths; do
  SCRIPT_PATH="${HOME}/.local/dotfiles/${SCRIPT_NAME}"
  if [[ -x "${SCRIPT_PATH}" ]]; then
    if [[ "${BASH_DEBUG}" == 1 ]]; then REPORT_DEBUG "source ${SCRIPT_PATH}"; fi
    source "${SCRIPT_PATH}"
  fi
done
unset SCRIPT_NAME SCRIPT_PATH

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

export SAGE_ATLAS_LIB=/usr/lib/   # do not build ATLAS
export SHELL=/bin/bash
# The end
