#!/bin/bash
#
# Enable this file by changing its permissions to executable.
#
# Warning: if BASH_QUIET is turned off, a number of things can break.

BASH_DEBUG=1
BASH_QUIET=1
BASH_LOG="${HOME}/bash_debug.log"
export BASH_DEBUG BASH_QUIET BASH_LOG
function REPORT_DEBUG() {
  if [[ "${BASH_DEBUG}" != 1  ]]; then return; fi
  if [[ "${BASH_LOG}"   != "" ]]; then printf "DEBUG: %s\n" "$*" >>"${BASH_LOG}"; fi
  if [[ "${BASH_QUIET}" != 1  ]]; then printf "DEBUG: %s\n" "$*"; fi
}
