#!/bin/bash

# Must source bash_functions first

set -o vi

# Require Append_path Prepend_path Unique_path

# Locations
function portable-env() {

  # Environment
  export PSCR APPS TEMPLATEPATH SYSTEMC_HOME CDPATH PATH MANPATH PERL5LIB

  PSCR="$(Realpath "${HOME}/.local")"
  APPS="$(Realpath "${PSCR}/apps")"
  DOTBIN="$(Realpath "${PSCR}/bin")"
  APPSBIN="${PSCR}/apps/bin"
  SYSTEMC_HOME="${PSCR}/apps/systemc"
  SYSTEMC_SRC="${PSCR}/src/systemc"
  Prepend_path PATH "${HOME}/.rvm/bin"
  Prepend_path PATH "/sbin"
  Prepend_path PATH "/bin"
  Prepend_path PATH "/usr/sbin"
  Prepend_path PATH "/usr/bin"
  Prepend_path PATH "/usr/local/sbin"
  Prepend_path PATH "/usr/local/bin"
  Prepend_path PATH "/opt/local/sbin"
  Prepend_path PATH "/opt/local/bin"
  Prepend_path PATH "/opt/homebrew/sbin"
  Prepend_path PATH "/opt/homebrew/bin"
  Prepend_path PATH "${APPSBIN}"
  Prepend_path PATH "${DOTBIN}"
  Prepend_path PATH "${HOME}/bin"
  PERL5LIB="$(Realpath "${PSCR}/lib")"
  TEMPLATEPATH="$(Realpath "${HOME}/templates")"
  TEMPLATEPATH="${TEMPLATEPATH}:$(Realpath "${HOME}/.local/templates")"
  TEMPLATEPATH="${TEMPLATEPATH}:$(Realpath "${HOME}/.local/apps/templates")"

  Unique_path PATH
  Unique_path MANPATH
  Unique_path TEMPLATEPATH

  export FAVS LESS CXX CC CMAKE_VERSION CMAKE_BUILD EDITOR VISUAL

  # Favorites
  FAVS="${HOME}"/Favorites
  mkdir -p "${FAVS}"
  CDPATH="."
  for dir in "${FAVS}" "${HOME}"; do
    Append_path CDPATH "${dir}"
  done

  # Affect applications
  LESS="-afrMRXj4x4"
  CMAKE_VERSION="3.19"
  CMAKE_BUILD="7"
  # Change following if have and prefer clang
  CC="clang"
  CXX="clang++"
  EDITOR="vim"
  VISUAL="vim"

}

portable-env
