#!/bin/bash

export CDPATH
function SetupPaths() {

  #-----------------------------------------------------------------------------
  if [[ $# -gt 0 ]]; then
    for dir in "${@}"; do
      if [[ -z "${dir}" ]]; then continue; fi
      COURSE="$(find "${HOME}" -type d -path '**/.snapshots' -prune -false -o "${dir}" 2>/dev/null)"
      if [[ -d "${COURSE}" ]]; then
        Prepend_path CDPATH "${COURSE}"
      fi
    done
  fi

  #-----------------------------------------------------------------------------
  # Add man page paths
  #-----------------------------------------------------------------------------
  for dir in \
    "/usr/share/man" \
    "/opt/local/man" \
    "/opt/local/share/man" \
    "/usr/local/share/man" \
    "/ext/linux/Ubuntu-20.04/usr/share/man" \
    "${HOME}/.local/man" \
    "${HOME}/man" \
    "./man" \
  ; do
    Prepend_path MANPATH "${dir}"
  done
  Unique_path MANPATH
  export MANPATH

}

SetupPaths esscpp syscfund tlm-2
