#!/bin/bash
#
# FILE: .bash_profile

# This script sources bashrc and ensure the home directory is setup properly.
export HOME USER
USER="$(whoami)"
HOME="$(getent passwd "${USER}" | cut -d: -f6 || true)"

# Get the aliases and functions
if [[ -f ~/.bashrc ]]; then
  # shellcheck source=/dev/null
  source ~/.bashrc
fi

# User specific environment and startup programs

if [[ -d ~/bin ]]; then
  mkdir -p   ~/bin
  chmod g+s  ~/bin
  chmod a+rx ~/bin
fi

if [[ "${HOME}" == "${LEAD}" && ! -d "${LEAD}/.local/bin" ]]; then
  # Leader needs to have accessible .local
  chmod g+s  "${LEAD}/.local"
  mkdir -p   "${LEAD}/.local/bin" "${LEAD}/.local/dotfiles"
  chmod a+rx "${LEAD}/.local/bin" "${LEAD}/.local/dotfiles"
  chmod a+x  "${LEAD}"
fi

if [[ -n "${LEAD}" ]]; then
  prepend_path PATH "${LEAD}/.local/bin"
  prepend_path PATH ~/bin # Allow user overrides
  MANPATH=~/man:"${LEAD}/.local/man:${LEAD}/.local/share/man:/usr/local/share/man:/usr/share/man"
fi
export MANPATH
