#!/bin/sh

if [[ -z "${ALIAS_SCRIPT}" && -n "${script}" ]]; then
  export ALIAS_SCRIPT
  ALIAS_SCRIPT="${script}"
fi
# enable color support of ls and also add handy aliases
test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"

alias ls='ls -BCF --color=always'
alias la='ls -A'
alias ll='ls -l'
alias dir='dir --color=auto'
alias m='less'
alias cls='clear'
alias vivado-setup='source "${APPS}"/xilinx/2020.1/Vivado/2020.1/settings64.sh'
export VI='vim'
function dotfile() {
  local f
  for f in "${HOME}/.$1" "${HOME}/.local/dotfiles/$1"; do
    if [[ -f "${f}" ]]; then
      echo "${f}"; return
    fi
  done
  echo "Unable to located ${f}" 1>&2
  ABORT
}
alias vial='"${VI}"    -f "$(dotfile bash_aliases)";   source "$(dotfile bash_aliases)"'
alias vibash='"${VI}"  -f "$(dotfile bashrc)";         source "$(dotfile bashrc)"'
alias vienv='"${VI}"   -f "$(dotfile bashenv)";        source "$(dotfile bashenv)"'
alias vifuncs='"${VI}" -f "$(dotfile bash_functions)"; source "${HOME}"/.bash_functions'
alias .alias='source "$(dotfile bash_aliases)"'
alias .bash='source  "$(dotfile bashrc)"'
alias .env='source   "$(dotfile bashenv)"'
alias .funcs='source "$(dotfile bash_functions)"'
alias aliases='alias | perl -pe "s/alias //;s/=.*//" | fmt'
alias funcs='declare -F|perl -pe "s/declare -f//;"|fmt'
alias tcpip='ifconfig | grep -i mask'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

