#!/bin/bash

export BASH_DEBUG=1
export BASH_QUIET=1
export BASH_LOG="${HOME}/bash_debug.log"
function REPORT_DEBUG() {
  if [[ "${BASH_DEBUG}" != 1  ]]; then return; fi
  if [[ "${BASH_LOG}"   != "" ]]; then printf "DEBUG: %s\n" "$*" >>"${BASH_LOG}"; fi
  if [[ "${BASH_QUIET}" != 1  ]]; then printf "DEBUG: %s\n" "$*"; fi
}
