#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Essential building blocks
#-------------------------------------------------------------------------------
LOCAL=~/.local
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Essential-IO"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Append_path"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Expand_path"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/FindScript"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Firstreal"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Has_path"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Load"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Prepend_path"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Realpath"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Remove_missing"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Remove_path"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Unique_path"

#-------------------------------------------------------------------------------
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Nargs"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Find"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Add_prefix"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Add_suffix"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Unique_list"

#-------------------------------------------------------------------------------
# Personal habits
#-------------------------------------------------------------------------------

# shellcheck disable=SC1091
source "${LOCAL}/scripts/j"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/lx"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/lns"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/h"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/show-colors"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Tcpip"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/dotfile"

function use-cmake() {
  # shellcheck disable=SC1091
  source "${LOCAL}/.local/bin/use-cmake"
}

# shellcheck disable=SC1091
source "${LOCAL}/bin/wd" -init

export DID_FUNCTIONS
DID_FUNCTIONS=1

# vim:nospell
