#!/usr/bin/env bash

#-------------------------------------------------------------------------------
# Essential building blocks
#-------------------------------------------------------------------------------
LOCAL=~/.local
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Essential-IO"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Essential-manip"

#-------------------------------------------------------------------------------
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Find"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Unique_list"

#-------------------------------------------------------------------------------
# Personal habits
#-------------------------------------------------------------------------------

# shellcheck disable=SC1091
source "${LOCAL}/scripts/j"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/lx"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/lns"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/h"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/show-colors"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/Tcpip"
# shellcheck disable=SC1091
source "${LOCAL}/scripts/dotfile"

function use-cmake() {
  # shellcheck disable=SC1091
  source "${LOCAL}/.local/bin/use-cmake"
}

# shellcheck disable=SC1091
source "${LOCAL}/bin/wd" -init

export DID_FUNCTIONS
DID_FUNCTIONS=1

# vim:nospell
