#!/bin/zsh

(return 0 2>/dev/null) && SOURCED=1 || SOURCED=0
if [[ ${SOURCED} == 0 ]]; then
  echo "Don't run $0, source it" >&2
  exit 1
fi
export SHELLNAME=zsh

alias ez='exec zsh'
alias 1p=op
alias 0p='eval $(op signin family_tx512)'
alias bc='shellcheck -s bash -xa -o all'
alias myip='ipconfig getifaddr en0'
alias font-sample="echo '#=0123456789_=-^+@auvwxy/\B&8b6ijl1|L_?9gqQO0op2Z75S'"
alias ipno='ifconfig|egrep "vmnet|(inet[ ])"'
alias week='date +%W'
alias tab='it tab'
alias flow=git-flow
alias %=_do
CPU=$(uname -p)
if [[ "${CPU}" == "arm" ]]; then
  alias oldbrew=/usr/local/bin/brew
fi
alias nvim='gvim -ngp'
export VI='vim'
export LOCAL EDITOR
alias view-systemc='"${EDITOR}" "${LOCAL}/src/systemc/src"'
function ViSrc() {
  local FILE
  FILE="$(Realpath "$1")"
  shift
  echo "${VI} -f $* ${FILE}"
  "${VI}" -f "$@" "${FILE}"
  if [[ ! -d "${FILE}" && -x "${FILE}" ]]; then
    echo "source \"${FILE}\""
    # shellcheck disable=SC1090
    source "${FILE}"
  fi
}
function viscr() {
  # shellcheck disable=SC2154,SC2312
  ViSrc "$(Firstreal ~/"scripts/$1" "${LOCAL}/scripts/$1")";
}
alias vial='ViSrc ~/.zsh_aliases'
alias vizsh='ViSrc ~/.zshrc'
alias vigit='ViSrc ~/.gitconfig'
alias vissh='ViSrc ~/.ssh/config'
alias vifuncs='ViSrc ~/.zsh_functions'
alias vimrc='ViSrc ~/.vimrc'
alias vienv='ViSrc ~/.zsh_env'
alias viobs='ViSrc ~/OBS/Doulos/.'
alias Exit="osascript -e 'tell application \"iTerm2\" to quit'; exit"
alias .alias='. ~/.zsh_aliases'
alias .zsh='. ~/.zshrc'
alias .env='. ~/.zsh_env'
alias .funcs='. ~/.zsh_functions'
alias aliases='alias | perl -pe "s/alias //;s/=.*//" | fmt'
function funcs() {
  # shellcheck disable=SC2312
  declare -f | perl -lane 'next unless m-^[[:alpha:]]{2,} *\(\) ?[\{]-;print $F[0]' | fmt
}
function agl()
{
  ag -l --nocolor "$@" | sort || true
}
function agL()
{
  ag -L --nocolor "$@" | sort || true
}
alias ag0='ag --depth=0'
alias ag1='ag --depth=0'
alias ag.='ag --depth=0 --hidden'
function agh() {
  ag -t -s -w --hidden --depth 1 "$@"
}

alias threagile='docker run --rm -it -v "$(pwd)":/app/work threagile/threagile'

function new() {
  NEWEST=~"/.newest"
  local e=0
  if [[ $# == 0 ]]; then
    # shellcheck disable=SC2154
    "${LOCAL}/bin/new"
  fi
  if [[ "$1" == "-e" ]]; then
    e=1
    shift
  fi
  if [[ $# -gt 0 ]]; then
    rm -f "${NEWEST}"
    if [[ ! ( "$*" =~ -q ) ]]; then
      echo "${LOCAL}/bin/new" "$@"
    fi
    # shellcheck disable=SC2312
    "${LOCAL}/bin/new" "$@" | tee "${NEWEST}"
  fi
  if [[ "${e}" == "1" && -r "${NEWEST}" ]]; then
    NEWF=$(perl -lane 'print $1 if m/^Created "([^"]+)"/'  "${NEWEST}")
    if [[ -r "${NEWF}" && ! -d "${NEWF}" ]]; then
      gvim -f "${NEWF}"
    fi
  fi
}


#PS1='\[\e[1;`pws2`m\]\s-\h(`uname`):`pwd2` \!%\[\e[0m\] '
#PS2='\[\e[1;`pws2`m\]\!>\[\e[0m\] '
#PS1='\u@\h:\w$(__git_ps1 " (%s)") $ '
#PROMPT_DIRTRIM=2
alias sane='reset; stty erase ^H'
function hclr() {
  cat /dev/null >~/"saved$1.history";
}
function hput() {
  history -a >~/"saved$1.history";
}
function hget() {
  history -n >~/"saved$1.history";
}
function hreduce() {
  hunique -o ~/"saved$1.history";
}
function m() {
  if [[ "$1" == '-nc' ]]; then
    env NOCOLOR=1 less "$@"
  else
    less "$@"
  fi
}
alias W='command -V';
alias F='file'
alias I='lipo -info'
alias info='info --vi-keys';
alias cls='/usr/bin/clear; ';
alias .bashrc='. ~/.bashrc';
alias dcblack='. ~/dcblack.bash'
alias 7za='7za a -t7z -m0=lzma -mx=9 -mfb=64 -md=32m -ms=on'

export LS_OPTS=-bhCF
export TREE_OPTS="-ACF --gitignore"
# shellcheck disable=SC2312
if [[ "$(uname -s)" == "Darwin" ]]; then
  # Macintosh specific
  alias msword="open -a 'Microsoft Word'"
  alias excel="open -a 'Microsoft Excel'"
  alias powerpoint="open -a 'Microsoft PowerPoint'"
  alias parallels="open -a 'Parallels Desktop'"
  alias eclipse="open -a eclipse"
  alias gls='/usr/local/bin/gls ${LS_OPTS} --color';
  alias ls='ls ${LS_OPTS}G';
  alias la='ls ${LS_OPTS}AG';
  export LSUSB='/usr/local/bin/lsusb'
  export GREP='/usr/bin/grep'
# alias make='gmake';
# alias gdb='lldb'
else
  alias ls='ls -bCF --color';
  alias la='ls ${LS_OPTS}A --color';
  alias make='make';
fi
alias tree='tree ${TREE_OPTS}';
alias st='set_title';
alias echoln='perl -e '"'"'printf qq{%s\n},join(qq{\n},@ARGV);'"'"

alias pushbw='pushd +1'
alias pushfw='pushd -0'
alias unsetenv="unset"
for n in 80 100 120 140 160; do
  # shellcheck disable=SC2139,SC2140
  alias "${n}"="ruler -n ${n}"
done
alias Mktree='mkdir -p a a/b1 a/b2 a/bin; touch a/b3.txt a/b1/c1.txt a/b1/c2.txt a/b2/c3.txt a/bin/dummy; chmod a+rx a/bin/dummy'
alias Mkvar='export A=a/bin:a/b1:a:a/b2:a/b1:a/b2/c3.txt:a:a/bin:a/bin/dummy'

function serialize() {
  for var in "$@"; do
    typeset -p "${var}" > "./serialized_${var}.sh"
  done
}

# function deserialize() {
#   declare() { builtin declare -g "$@"; }
#   typeset() { builtin typeset -g "$@"; }
#   for var in "$@"; do
#     # shellcheck disable=SC1090
#     source "./serialized_${var}.sh"
#   done
#   unset -f declare typeset
# }

#EOF ~/.bash_aliases vim:nospell
